### PR TITLE
Support creating new DM channels.

### PR DESCRIPTION
**Pull request by hodgman**
Usage:

```
                if not message.author.channel then
                    client:openDirectMessage(message.author.id)
                end
                if message.author.channel then
                    message.author.channel:sendMessage(content)
                else
                    message:reply('For some reason I cannot direct message you! Please send me a direct message to open the channel for me :kissing_heart:')
                end
```

### CODE REVIEW

**Comment by satom99** [comment]
Firstly, thanks for the PR :yum: ! Are you on the latest lit-published version? I am pretty sure I fixed the roles issue already. About creating private channels, I guess having a `sendMessage` method under `User` would make more sense as you would be able to just pass `sendMessage` arguments as if it was `Channel`'s method and it would create the channel itself if not present. And as a side-note, using `local` for `dmChannel` would be better too.

**Comment by hodgman** [comment]
Haha yeah the missing local on `dmChannel` is a bug :) I decided to use litcord because I need more practice in Lua for other projects, so I can avoid these common pitfalls. I also still write semicolons unconsciously!

I figured there would be a nicer way to integrate this into your API -- my example usage of forcing the user to perform a null check is kinda abrasive. My example also has two null checks in the user code. I'm not sure how to reproduce it, but I did see a case where the second check actually was required, and the bot posted a `For some reason I cannot direct message you!` message...

Having `message.author:sendMessage` automatically open a new DM channel when required would be _much_ cleaner than the solution in this commit.

As for the other issue with roles, I was working off a github version -- I'm pretty sure it's the version  that's forked in `hodgman:master` at the moment.

**Comment by satom99** [comment]
I am pretty sure the double check is required because there may be a delay from when the DM object is `dispatched` to the `CHANNEL_CREATE` event to when you are trying to send a message through that channel - so that you are trying to send a message before the DM's `Channel` structure is Cached. That's most likely an _issue_ with Lua, I am not sure myself about that though. That being said, I will be adding a `sendMessage` method to the `User` structure that handles DM creation if not present.

About roles, I am running latest pushed code and both methods work fine. I am not getting any role removed except the one expected. Now, you may try pulling latest files from the `master` branch and try again, once that is solved I guess we may then proceed and successfully close this PR!

**Update**: `User`'s `sendMessage` [method](https://github.com/satom99/litcord/blob/master/litcord/structures/User.lua#L13) is now added.

**Comment by hodgman** [comment]
Thanks :+1:

**Pull request closed without merging**
